"""PostGIS-backed cadastral repository.

Implements the same :class:`~app.repositories.base.CadastreRepository` contract
as the in-memory store, so services and routers are unaware of which backend is
active.

Spatial handling
----------------
Footprints are persisted in **WGS84 (SRID 4326)** — the same GeoJSON the
application already exchanges, so no lossy round-trip is introduced. Geometry
is adapted with :func:`shapely.geometry.shape` directly from the GeoJSON
mapping, deliberately bypassing the engine's local planar transform, which
exists for metric maths only and must never be stored.

Each geometry column has a generated, GIST-indexed companion in
``METRIC_SRID``. Use that for measurement; ``ST_Area`` on the 4326 column
returns square degrees, not square metres.

Transactions
------------
A repository is bound to one :class:`~sqlalchemy.orm.Session`. Writes flush
immediately so subsequent reads in the same unit of work see them; the commit
boundary is owned by :func:`app.db.session.get_db_session` (per request) or
:func:`app.db.session.session_scope` (scripts and tests).
"""
from __future__ import annotations

import logging
from collections.abc import Iterable, Mapping
from typing import Any

import sqlalchemy as sa
from geoalchemy2 import WKBElement
from geoalchemy2.shape import to_shape
from shapely.geometry import shape
from sqlalchemy.orm import Session

from app.db.models import COLLECTION_MODELS
from app.db.types import GEOGRAPHIC_SRID
from app.models.schemas import SearchResult
from app.repositories.base import (
    COLLECTIONS,
    SEARCH_ORDER,
    SEARCHABLE_COLLECTIONS,
    CadastreRepository,
    DuplicateRecord,
    RecordNotFound,
)
from app.services.storage import (
    DATE_FIELD,
    GEOMETRY_FIELDS,
    JSON_FIELD,
    TIMESTAMP_FIELDS,
    normalise_changes,
    to_date,
    to_iso,
    to_iso_timestamp,
)

log = logging.getLogger(__name__)

#: Never written from application records: generated by the database.
DERIVED_COLUMNS = {
    "geometry_metric",
    "footprint_metric",
    "geometry_3d_metric",
}


class PostgresCadastreRepository(CadastreRepository):
    """SQLAlchemy/PostGIS implementation of the repository contract."""

    def __init__(self, session: Session) -> None:
        self.session = session

    # ------------------------------------------------------------------
    # mapping between GeoJSON records and rows
    # ------------------------------------------------------------------

    def _model(self, kind: str):
        try:
            return COLLECTION_MODELS[kind]
        except KeyError:
            raise KeyError(f"unknown collection {kind!r}") from None

    def _to_row(self, kind: str, record: Mapping[str, Any]) -> dict[str, Any]:
        """GeoJSON record -> column values, encoding geometry for PostGIS."""
        model = self._model(kind)
        columns = {c.name for c in model.__table__.columns} - DERIVED_COLUMNS
        row: dict[str, Any] = {
            k: v for k, v in record.items() if k in columns and v is not None
        }

        geom_field = GEOMETRY_FIELDS.get(kind)
        if geom_field and geom_field in columns:
            geo = record.get(geom_field)
            if geo:
                # Adapt the GeoJSON directly. The engine's local planar
                # transform exists for metric maths and must never be stored.
                row[geom_field] = WKBElement(shape(geo).wkb, srid=GEOGRAPHIC_SRID)

        if kind in JSON_FIELD:
            attr, key = JSON_FIELD[kind]
            if key in record:
                row[attr] = record[key]
        if kind in DATE_FIELD:
            attr, key = DATE_FIELD[kind]
            if record.get(key):
                row[attr] = to_date(record[key])
        return row

    def _to_record(self, kind: str, row: Any) -> dict[str, Any]:
        """ORM row -> GeoJSON record matching the in-memory shape exactly."""
        model = self._model(kind)
        geom_field = GEOMETRY_FIELDS.get(kind)
        record: dict[str, Any] = {}
        for column in model.__table__.columns:
            name = column.name
            if name in DERIVED_COLUMNS:
                continue
            value = getattr(row, name, None)
            if name == geom_field and value is not None:
                record[name] = _to_geojson(to_shape(value))
            elif name in TIMESTAMP_FIELDS:
                # Normalise so this backend returns the same record shape as the
                # in-memory store (ISO strings, not datetimes).
                record[name] = to_iso_timestamp(value)
            else:
                record[name] = value
        if kind in JSON_FIELD:
            attr, key = JSON_FIELD[kind]
            record[key] = getattr(row, attr, None)
        if kind in DATE_FIELD:
            attr, key = DATE_FIELD[kind]
            record[key] = to_iso(getattr(row, attr, None))
        if geom_field:
            record.setdefault(geom_field, None)
        return record

    # ------------------------------------------------------------------
    # reads
    # ------------------------------------------------------------------

    def records(self, kind: str) -> list[dict[str, Any]]:
        model = self._model(kind)
        rows = self.session.execute(sa.select(model)).scalars().all()
        return [self._to_record(kind, r) for r in rows]

    def find_by_id(self, object_id: str) -> tuple[str, dict[str, Any]] | None:
        for collection in SEARCHABLE_COLLECTIONS:
            model = self._model(collection)
            row = self.session.get(model, object_id)
            if row is not None:
                return collection, self._to_record(collection, row)
        return None

    def search(self, ident: str) -> SearchResult:
        """Substring search, mirroring the in-memory implementation's order.

        Ordering is explicit rather than relying on row order so results match
        the demo store exactly.
        """
        q = ident.strip().lower()
        for kind, collection in SEARCH_ORDER:
            model = self._model(collection)
            rows = (
                self.session.execute(
                    sa.select(model).order_by(model.__table__.c.id)
                )
                .scalars()
                .all()
            )
            for row in rows:
                # `kind` is the API-facing label ("parcel"); `collection` is the
                # storage name ("parcels") the model lookup needs.
                record = self._to_record(collection, row)
                hay = " ".join(
                    str(record.get(f, ""))
                    for f in (
                        "id",
                        "parcel_id",
                        "building_id",
                        "prototype_ulpin",
                        "unit_label",
                        "type",
                    )
                ).lower()
                if q in hay:
                    related = (
                        {
                            "children": [
                                p["id"]
                                for p in self.records("properties")
                                if p.get("building_id") == record.get("building_id")
                            ]
                        }
                        if kind == "building"
                        else {}
                    )
                    return SearchResult(kind=kind, record=record, related=related)
        raise RecordNotFound(ident)

    # ------------------------------------------------------------------
    # writes
    # ------------------------------------------------------------------

    def add(self, kind: str, record: dict[str, Any]) -> dict[str, Any]:
        model = self._model(kind)
        # The in-memory adapter raises `DuplicateRecord` here, and it must raise
        # the same error for the same input. Relying on the primary key to fail
        # at commit time instead produced an unhandled `IntegrityError` -- a 500
        # on one backend and a silently duplicated row on the other.
        object_id = record.get("id")
        if object_id is not None and self.session.get(model, object_id) is not None:
            raise DuplicateRecord(kind, object_id)
        row = model(**self._to_row(kind, record))
        self.session.add(row)
        self.session.flush()
        return self._to_record(kind, row)

    def add_all(self, kind: str, records: Iterable[dict[str, Any]]) -> None:
        model = self._model(kind)
        for record in records:
            object_id = record.get("id")
            if (
                object_id is not None
                and self.session.get(model, object_id) is not None
            ):
                raise DuplicateRecord(kind, object_id)
            self.session.add(model(**self._to_row(kind, record)))
        self.session.flush()

    def update(
        self, kind: str, object_id: str, changes: Mapping[str, Any]
    ) -> dict[str, Any] | None:
        model = self._model(kind)
        row = self.session.get(model, object_id)
        if row is None:
            return None
        encoded = self._to_row(kind, normalise_changes(kind, changes))
        for name, value in encoded.items():
            setattr(row, name, value)
        self.session.flush()
        return self._to_record(kind, row)

    def delete(self, kind: str, object_id: str) -> bool:
        model = self._model(kind)
        row = self.session.get(model, object_id)
        if row is None:
            return False
        self.session.delete(row)
        self.session.flush()
        return True

    def clear(self, kind: str) -> None:
        self.session.execute(sa.delete(self._model(kind)))
        self.session.flush()

    def replace_all(self, data: dict[str, list[dict[str, Any]]]) -> None:
        """Truncate and reload, used by demo seeding.

        Ordered so that foreign keys stay satisfied while truncating, and so the
        append-only history is cleared **last**: an audit trail that outlives a
        demo reload would describe a scene that no longer exists.
        """
        for kind in (
            "provenance_links",
            "cadastral_changes",
            "review_decisions"
            "review_cases",
            "geometry_versions",
            "issues",
            "sources",
            "properties",
            "floors",
            "infrastructure",
            "buildings",
            "parcels",
        ):
            if kind in data or kind in COLLECTIONS:
                self.session.execute(sa.delete(self._model(kind)))
        self.session.flush()
        for kind in COLLECTIONS:
            rows = data.get(kind) or []
            if rows:
                self.add_all(kind, rows)
        self.session.flush()

    # ------------------------------------------------------------------
    # spatial
    # ------------------------------------------------------------------

    def spatial_query(
        self,
        kind: str,
        geojson_geometry: Mapping[str, Any],
        *,
        relationship: str = "intersects",
    ) -> list[dict[str, Any]]:
        """Find records whose footprint stands in ``relationship`` to a GeoJSON polygon.

        The predicate runs in SRID 4326, which is correct for topology: it is
        purely combinatorial and does not depend on a projection.

        Parameters
        ----------
        relationship:
            One of ``intersects``, ``contains``, ``within``, ``overlaps``.
        """
        allowed = {"intersects", "contains", "within", "overlaps"}
        if relationship not in allowed:
            raise ValueError(
                f"unsupported relationship {relationship!r}; expected one of {sorted(allowed)}"
            )
        model = self._model(kind)
        geom_field = GEOMETRY_FIELDS[kind]
        probe = WKBElement(shape(geojson_geometry).wkb, srid=GEOGRAPHIC_SRID)
        statement = sa.select(model).where(
            getattr(model, geom_field).ST_Intersects(probe)
            if relationship == "intersects"
            else sa.text(f"{relationship.upper()}(:probe, {geom_field})").bindparams(
                probe=probe
            )
        )
        rows = self.session.execute(statement).scalars().all()
        return [self._to_record(kind, r) for r in rows]

    def metric_area_m2(self, kind: str, object_id: str) -> float | None:
        """Area in square metres via the generated metric column.

        Never reads ``ST_Area`` off the geographic column, which would return
        square degrees.
        """
        model = self._model(kind)
        metric_field = f"{GEOMETRY_FIELDS[kind]}_metric"
        return self.session.execute(
            sa.select(sa.func.ST_Area(getattr(model, metric_field))).where(
                model.__table__.c.id == object_id
            )
        ).scalar()

    def health_check(self) -> dict[str, Any]:
        from app.db.session import check_database_health

        result = check_database_health()
        result["backend"] = "postgres"
        try:
            counts = {
                kind: self.session.execute(
                    sa.select(sa.func.count()).select_from(self._model(kind))
                ).scalar_one()
                for kind in COLLECTIONS
            }
            result["collections"] = counts
        except Exception as exc:  # noqa: BLE001 - health must never raise
            result["collections_error"] = f"{type(exc).__name__}: {exc}"[:200]
        return result


def _to_geojson(polygon) -> dict[str, Any]:
    """Shapely polygon -> GeoJSON mapping, preserving coordinate order."""
    return {
        "type": "Polygon",
        "coordinates": [[list(pt) for pt in polygon.exterior.coords]],
    }
