"use client";
import dynamic from "next/dynamic";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Boxes, Building2, ChevronRight, Database, Layers3, Loader2, MapPinned, Radar, Search, ShieldCheck, SlidersHorizontal, Sparkles, TowerControl, Upload, Zap } from "lucide-react";
import { API, api } from "../lib/api";

const CesiumMap = dynamic(()=>import("../components/CesiumMap"),{ssr:false,loading:()=> <div className="grid h-full place-items-center text-slate-400"><Loader2 className="animate-spin"/> Initialising 3D engine…</div>});
type RecordAny = Record<string,any>;
type Data = {parcels:RecordAny[];buildings:RecordAny[];properties:RecordAny[];infrastructure:RecordAny[];issues:RecordAny[];analytics:RecordAny|null};
const blank:Data={parcels:[],buildings:[],properties:[],infrastructure:[],issues:[],analytics:null};
const nav=[['Data Sources',Database],['Parcels',MapPinned],['Buildings',Building2],['Floors',Layers3],['Property Volumes',Boxes],['Underground Infrastructure',TowerControl],['Validation',AlertTriangle],['ULPIN Search',Search],['Analysis',Radar]];

export default function CommandCenter(){
 const [data,setData]=useState<Data>(blank),[selected,setSelected]=useState<RecordAny|null>(null),[focus,setFocus]=useState<RecordAny|null>(null),[query,setQuery]=useState(""),[floor,setFloor]=useState<number|"all">("all"),[underground,setUnderground]=useState(true),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[active,setActive]=useState("Property Volumes");
 const reload=useCallback(async()=>{try{const [parcels,buildings,properties,infrastructure,issues,analytics]=await Promise.all([api<RecordAny[]>("/parcels"),api<RecordAny[]>("/buildings"),api<RecordAny[]>("/properties"),api<RecordAny[]>("/infrastructure"),api<RecordAny[]>("/validation/issues"),api<RecordAny>("/analytics/summary")]);setData({parcels,buildings,properties,infrastructure,issues,analytics});}catch(e){setNotice(e instanceof Error?e.message:"Unable to reach API");}},[]);
 useEffect(()=>{reload()},[reload]);
 async function action(label:string,path:string){setBusy(label);setNotice("");try{const result=await api<RecordAny>(path,{method:path.includes("demo")?"GET":"POST",body:path.includes("demo")?undefined:"{}"});await reload();setNotice(result.message || result.label || `${label} completed.`)}catch(e){setNotice(e instanceof Error?e.message:"Request failed")}finally{setBusy("")}}
 async function search(e:React.FormEvent){e.preventDefault();if(!query.trim())return;setBusy("Search");try{const x=await api<RecordAny>(`/ulpin/${encodeURIComponent(query.trim())}`);setSelected(x.record);setFocus({...x.record});setNotice(`Located ${x.kind}: ${x.record.unit_label || x.record.building_id || x.record.parcel_id || x.record.id}`)}catch(e){setNotice(e instanceof Error?e.message:"Not found")}finally{setBusy("")}}
 async function uploadSource(file?:File){if(!file)return;setBusy("Import source");try{const form=new FormData();form.append("file",file);const res=await fetch(`${API}/import/source`,{method:"POST",body:form});const result=await res.json();if(!res.ok)throw new Error(result.detail||"Import failed");setNotice(result.note||`${file.name} accepted`)}catch(e){setNotice(e instanceof Error?e.message:"Import failed")}finally{setBusy("")}}
 function pick(r:RecordAny){setSelected(r);setFocus({...r})}
 const counts=useMemo(()=>({critical:data.issues.filter(x=>x.severity==='CRITICAL').length,warning:data.issues.filter(x=>x.severity==='WARNING').length,info:data.issues.filter(x=>x.severity==='INFO').length}),[data.issues]);
 return <main className="grid h-screen min-w-[1120px] grid-cols-[232px_1fr_315px] grid-rows-[58px_1fr_178px] bg-[#061119] text-[#d8e6e6]">
   <header className="col-span-3 flex items-center border-b border-[#28434b] bg-[#081820] px-5">
     <div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center border border-[#5ac3b5] bg-[#0c3538] text-[#74e0d0]"><Layers3 size={19}/></div><div><div className="text-sm font-bold tracking-[.18em] text-white">V-CAD</div><div className="text-[9px] tracking-[.15em] text-[#78a9a8]">3D ULPIN & VOLUMETRIC CADASTRE</div></div></div>
     <div className="ml-8 border-l border-[#294047] pl-5 text-xs text-[#8eadae]">Ministry of Rural Development <span className="mx-2 text-[#46656b]">/</span> DoLR <span className="ml-2 rounded border border-[#48646a] px-1.5 py-0.5 text-[10px] text-[#b0c9c7]">PROTOTYPE</span></div>
     <form onSubmit={search} className="relative ml-auto w-[390px]"><Search className="absolute left-3 top-2.5 text-[#6c9091]" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ULPIN, parcel, building or apartment" className="h-9 w-full border border-[#35535a] bg-[#0b2028] pl-9 pr-3 text-xs outline-none placeholder:text-[#637e80] focus:border-[#62cdbd]"/></form>
     <div className="ml-4 flex items-center gap-2 text-[10px] text-[#77d7bd]"><span className="h-2 w-2 rounded-full bg-[#52d39e]"/> DEMO ENGINE ONLINE</div>
   </header>
   <aside className="row-span-2 border-r border-[#28434b] bg-[#071820] py-4">
     <div className="px-4 pb-2 text-[10px] font-semibold tracking-[.16em] text-[#6e9293]">CADASTRAL WORKSPACE</div>
     <nav>{nav.map(([label,Icon])=><button key={label as string} onClick={()=>setActive(label as string)} className={`flex w-full items-center gap-3 border-l-2 px-4 py-2.5 text-left text-xs ${active===label?'border-[#62cdbd] bg-[#113038] text-[#dffdf5]':'border-transparent text-[#94afb1] hover:bg-[#0c222b]'}`}><Icon size={15}/>{label as string}{label==='Validation' && counts.critical>0?<span className="ml-auto rounded bg-[#713a31] px-1.5 text-[10px] text-[#ffb4a6]">{counts.critical}</span>:null}</button>)}</nav>
     <div className="mx-4 mt-6 border-t border-[#28434b] pt-4"><div className="mb-2 text-[10px] tracking-[.14em] text-[#6e9293]">DATA INGESTION</div><button onClick={()=>action("Load Demo City","/demo/load")} disabled={!!busy} className="flex w-full items-center justify-center gap-2 border border-[#4db4a6] bg-[#10383b] py-2 text-xs font-semibold text-[#9af1df] hover:bg-[#16484a]"><Zap size={14}/>{busy==='Load Demo City'?"Loading…":"Load Demo City"}</button><button onClick={()=>action("Generate 3D ULPIN","/ulpin/generate")} disabled={!!busy} className="mt-2 flex w-full items-center justify-center gap-2 border border-[#42646a] bg-[#0c252d] py-2 text-xs text-[#bcdbd7] hover:border-[#60c8b8]"><ShieldCheck size={14}/>{busy==='Generate 3D ULPIN'?"Generating…":"Generate 3D ULPIN"}</button><label className="mt-2 flex cursor-pointer items-center justify-center gap-2 border border-dashed border-[#42646a] py-2 text-[10px] text-[#9cbbba] hover:border-[#64caba]"><Upload size={13}/>Import GeoJSON / CSV / plans<input onChange={e=>uploadSource(e.target.files?.[0])} className="hidden" type="file" accept=".geojson,.json,.csv,.las,.laz,.ply"/></label><p className="mt-2 text-[10px] leading-4 text-[#6f9294]">P-001 / B-001: 16 apartments, basement and utility corridor. Point clouds register as a processing source in this offline demo.</p></div>
   </aside>
   <section className="relative min-w-0 overflow-hidden bg-[#07151d]">
     <CesiumMap {...data} selected={selected} focus={focus} floor={floor} underground={underground} onPick={pick}/>
     <div className="absolute left-4 top-4 panel w-[220px] p-3 shadow-2xl"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-[.14em] text-[#92b7b5]">SPATIAL CONTROLS</span><SlidersHorizontal size={14} className="text-[#69cbbd]"/></div><div className="mt-3 flex gap-1">{["all",-1,1,2,3,4,5,6,7,8].map(v=><button onClick={()=>setFloor(v as number|"all")} key={String(v)} className={`min-w-6 border px-1 py-1 text-[9px] ${floor===v?'border-[#65cdbc] bg-[#155052] text-white':'border-[#345057] text-[#9bb5b4]'}`}>{v==='all'?'ALL':v===-1?'B':v}</button>)}</div><label className="mt-3 flex cursor-pointer items-center justify-between text-[11px] text-[#a9c3c2]"><span>Underground layer</span><input checked={underground} onChange={e=>setUnderground(e.target.checked)} type="checkbox" className="accent-[#59c7b6]"/></label></div>
     <div className="absolute bottom-4 left-4 flex items-center gap-2 bg-[#06151bd9] px-3 py-2 text-[10px] text-[#93b4b3]"><span className="h-2 w-2 bg-[#3cb5a5]"/> mapped volume <span className="ml-2 h-2 w-2 bg-[#f1a61c]"/> review required <span className="ml-2 h-2 w-2 bg-[#d89936]"/> utility</div>
     {notice?<div className="absolute bottom-4 left-1/2 max-w-[520px] -translate-x-1/2 border border-[#496870] bg-[#0c2229] px-4 py-2 text-xs text-[#d1e2e1] shadow-xl">{notice}</div>:null}
   </section>
   <aside className="border-l border-[#28434b] bg-[#071820] p-4 thin-scroll overflow-y-auto">
     <div className="mb-4 flex items-center justify-between"><span className="text-[10px] font-bold tracking-[.16em] text-[#84a9aa]">OBJECT INSPECTOR</span><span className="rounded border border-[#315159] px-1.5 py-0.5 text-[9px] text-[#74d8c8]">LIVE</span></div>
     {!selected?<div className="mt-16 text-center text-xs leading-5 text-[#719092]"><MapPinned className="mx-auto mb-3 text-[#3e696d]" size={30}/>Select a property volume in the 3D view or use ULPIN Search.</div>:<Inspector item={selected}/>} 
     <div className="mt-6 border-t border-[#29434a] pt-4"><div className="mb-3 text-[10px] font-bold tracking-[.14em] text-[#83a7a8]">VERTICAL INSPECTOR</div><div className="relative ml-4 border-l border-[#3c5e63] py-1">{['+20m','+15m','+10m','+5m','0m','−5m','−10m'].map((z,i)=><div key={z} className="relative flex h-7 items-center pl-4 text-[10px] text-[#91adac]"><span className={`absolute -left-1.5 h-3 w-3 rounded-full border ${i===4?'border-[#65cdbc] bg-[#174849]':'border-[#4b6a6b] bg-[#0a2027]'}`}/>{z}<span className="ml-3 text-[#648283]">{i<4?'BUILDING':i===4?'GROUND':i===5?'BASEMENT':'UTILITY'}</span></div>)}</div></div>
   </aside>
   <section className="col-span-2 border-t border-[#28434b] bg-[#081820] p-3">
    <div className="grid h-full grid-cols-[1.08fr_1.25fr_.9fr] gap-4">
      <div className="border-r border-[#29434a] pr-4"><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-bold tracking-[.15em] text-[#87adac]">TOPOLOGY VALIDATION</span><button onClick={()=>action("Run validation","/validation/run")} className="text-[10px] text-[#75dccb] hover:text-white">{busy==='Run validation'?"Running…":"RUN CHECKS"}</button></div><div className="flex gap-2"><Metric label="CRITICAL" value={counts.critical} color="text-[#ff8f7b]"/><Metric label="WARNING" value={counts.warning} color="text-[#f2bd61]"/><Metric label="INFO" value={counts.info} color="text-[#8fc6dd]"/></div><div className="mt-2 max-h-[78px] space-y-1 overflow-auto thin-scroll">{data.issues.slice(0,4).map(issue=><button key={issue.id} onClick={()=>{setFocus({...issue,geometry_3d:issue.geometry});setSelected(issue)}} className="flex w-full items-center gap-2 text-left text-[10px] text-[#a8c0bf] hover:bg-[#103038]"><AlertTriangle size={11} className={issue.severity==='CRITICAL'?'text-[#fc806d]':'text-[#e8b85e]'}/><span className="truncate">{issue.issue_type.replaceAll('_',' ')}</span><ChevronRight className="ml-auto" size={12}/></button>)}</div></div>
      <div className="border-r border-[#29434a] pr-4"><div className="mb-2 text-[10px] font-bold tracking-[.15em] text-[#87adac]">AUTOMATION PIPELINE</div><div className="grid grid-cols-3 gap-2">{[['Building extraction','97.4%','/processing/building-extraction'],['Floor segmentation','91.8%','/processing/floor-segmentation'],['Vertical delineation','99.1%','/processing/vertical-delineation']].map(([a,b,path])=><button onClick={()=>action(a,path)} key={a} className="border border-[#2b4a51] bg-[#0a2027] p-2 text-left hover:border-[#4fb9a9]"><Sparkles size={13} className="mb-1 text-[#66c9ba]"/><div className="text-[9px] text-[#a3bfbd]">{a}</div><div className="mt-1 text-xs text-[#daf4ed]">{b}</div></button>)}</div><div className="mt-2 text-[9px] text-[#668587]">Model/prototype confidence. Low confidence is flagged for human review.</div></div>
      <div><div className="mb-2 text-[10px] font-bold tracking-[.15em] text-[#87adac]">CADASTRAL SNAPSHOT</div><div className="grid grid-cols-3 gap-y-2">{[['PARCELS',data.analytics?.parcels],['BUILDINGS',data.analytics?.buildings],['VOLUMES',data.analytics?.property_volumes],['APARTMENTS',data.analytics?.apartments],['UG ASSETS',data.analytics?.underground_assets],['AVG AI',data.analytics?`${data.analytics.average_confidence}%`:undefined]].map(([l,v])=><div key={l as string}><div className="text-lg font-semibold text-[#e1f0ee]">{v ?? '—'}</div><div className="text-[8px] tracking-wide text-[#759596]">{l}</div></div>)}</div></div>
    </div>
   </section>
 </main>
}
function Metric({label,value,color}:{label:string;value:number;color:string}){return <div className="border border-[#2a464d] bg-[#0a1e25] px-2 py-1"><div className={`text-base font-bold ${color}`}>{value}</div><div className="text-[8px] tracking-wide text-[#759596]">{label}</div></div>}
function Inspector({item}:{item:RecordAny}){const fields=[['Prototype 3D ULPIN',item.prototype_ulpin],['Parent Parcel',item.parent_parcel_id || item.parcel_id],['Building',item.building_id],['Floor / Level',item.floor_number],['Property Type',item.property_type || item.type],['Area',item.area_m2?`${item.area_m2} m²`:item.area?`${item.area} m²`:null],['Volume',item.volume_m3?`${item.volume_m3} m³`:null],['Z Range',item.z_min!==undefined?`${item.z_min}m → ${item.z_max}m`:null],['Geometry Hash',item.geometry_hash],['Confidence',item.confidence?`${(item.confidence*100).toFixed(1)}%`:null]];return <><div className="border border-[#31525a] bg-[#0a222a] p-3"><div className="flex items-start gap-2"><ShieldCheck className={item.status==='HUMAN REVIEW REQUIRED'?'text-[#efb757]':'text-[#69d3be]'} size={18}/><div><div className="text-sm font-semibold text-white">{item.unit_label || item.building_id || item.parcel_id || item.id}</div><div className="mt-1 text-[9px] tracking-[.12em] text-[#75a5a2]">{item.status || 'REGISTERED'} {item.status==='HUMAN REVIEW REQUIRED'?'• HUMAN REVIEW REQUIRED':''}</div></div></div></div><dl className="mt-4 space-y-2">{fields.filter(([,v])=>v!==null&&v!==undefined).map(([k,v])=><div key={k as string} className="border-b border-[#203b42] pb-2"><dt className="text-[9px] uppercase tracking-[.12em] text-[#69898a]">{k}</dt><dd className="mt-0.5 break-all text-xs text-[#d3e2e0]">{String(v)}</dd></div>)}</dl><p className="mt-4 text-[9px] leading-4 text-[#6f9192]">Prototype 3D ULPIN is a deterministic spatial identifier for this demonstration; it is not an official Government of India ULPIN.</p></>}
